<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>McpForUnityAgent</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <EmbeddedResource Remove="artifacts\**" />
    <None Remove="artifacts\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
